[simulation]
unit_length_au          = 93.0                                                                    #necessary
unit_mass_msun          = 1.2                                                                     #necessary
component               = ["dust", "gas"]                                                                 #necessary/to_be_improved_with_section?
output_dir              = "example/radmc3d_test"                                 #optional
# simulation_files_only   = false                                                                   #optional
processing              = [                                                                     #optional/to_be_improved?
    # {mode = "identity"},
    {mode="builtin", input_number=0, input_dir="tests/data/idefix_1_dust_fluid", internal_rho=2.0},
    {mode="phi_expansion", nphi=128},
    # {mode = "mask_inner", inner_edge = 1.5},
]

[dust.opacity]
mix                     = "birnstiel2018"                                                           #necessary
# rho                     = "unset"                                                                    #optional/None/to_be_improved?
# smoothing               = false                                                                   #optional/to_be_tested

[radmc3d]                                                                                       #optional
modified_random_walk    = 1
iranfreqmode            = 1
istar_sphere            = 1
tgas_eq_tdust           = 1
rto_style               = 3
nphot                   = 10
nphot_scat              = 10

[stars]
# M_star                  = 1.2                                                                     #to_be_improved/optional/unit_mass_msun?
R_star                  = 2.0                                                                     #necessary_if_star
T_star                  = 7000.0                                                                  #necessary_if_star
# mu_star                 = 1.37                                                                    #optional

# [wavelength_micron]
# min                     = 1                                                                                 #optional
# max                     = 10_000                                                                            #optional
# N                       = 200                                                                               #optional

[gas]                                                                                                       #necessary_if_gas
species                 = "co"                                                                              

[gas.number_density]
processing              = [
    {mode="prodimo", input_dir="path_to_prodimo_model_directory"},
    {mode="midplane_symmetry"},
    {mode="phi_expansion", nphi=128},
]
