[simulation]
on                      = 0                                                                     #necessary
input_dir               = "tests/data/idefix_1_dust_fluid"                                         #necessary
unit_length_au          = 93.0                                                                    #necessary
unit_mass_msun          = 1.2                                                                     #necessary
processing              = "template:phi_expansion"                                                  #optional/to_be_improved?
component               = ["dust", "gas"]                                                                 #necessary/to_be_improved_with_section?
internal_rho            = 2.0                                                                     #to_be_improved?
output_dir              = "tests/data/idefix_1_dust_fluid/radmc3d_ref"                                 #optional
simulation_files_only   = false                                                                   #optional

[dust.opacity]
mix                     = "birnstiel2018"                                                           #necessary
rho                     = "unset"                                                                    #optional/None/to_be_improved?
smoothing               = false                                                                   #optional/to_be_tested

[radmc3d]                                                                                       #optional
modified_random_walk    = 1
iranfreqmode            = 1
istar_sphere            = 1
tgas_eq_tdust           = 1
rto_style               = 3
nphot                   = 10
nphot_scat              = 10

[stars]
M_star                  = 1.2                                                                     #to_be_improved/optional/unit_mass_msun?
R_star                  = 2.0                                                                     #necessary_if_star
T_star                  = 7000.0                                                                  #necessary_if_star
mu_star                 = 1.37                                                                    #optional

[wavelength_micron]                                                                             #optional
lambda_min              = 1
lambda_max              = 10000
Nlam                    = 200

[gas]                                                                                                       #necessary_if_gas
species                 = "co"                                                                              

[gas.abundance]
mode                    = "constant"
value                   = 1e-4                                                                           
